version: "3.9"

services:
  app:
    container_name: laravel-app
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["/bin/sh", "-c", "composer run-script post-autoload-dump && apache2-foreground"]
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:uDVLCK/eZSzWEtwarkoVqN5dBzkjupCl7LxbAacvUAk=
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: geotager
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - laravel-net

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: geotager
    ports:
      - "5433:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - laravel-net

networks:
  laravel-net:

volumes:
  postgresdata: